#!/usr/bin/env python3
"""
Storybook Edge Blender
=======================

Softens the hard rectangular edges of AI-generated illustrations (e.g. images
generated by ChatGPT / DALL-E, Midjourney, etc.) so they blend naturally into
a storybook page instead of looking like a "sticker" with a sharp
white-background cutoff.

The script reads every image from an input folder, feathers/blurs its edges,
and writes a transparent-background PNG to an output folder.

Basic usage:
    python feather_edges.py
    python feather_edges.py --input-dir Input --output-dir Output
    python feather_edges.py --mode fade --fade-percent 15
    python feather_edges.py --mode mirror-fade --mirror-percent 12

See README.md for a full explanation of what each mode does, why it exists,
and its current limitations.
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Feather/blur the edges of images so they blend into a storybook page."
    )
    parser.add_argument(
        "--input-dir", "-i", default="Input",
        help="Folder to read source images from (default: 'Input').",
    )
    parser.add_argument(
        "--output-dir", "-o", default="Output",
        help="Folder to write processed images to (default: 'Output').",
    )
    parser.add_argument(
        "--mode", "-m", choices=["fade", "mirror-fade"], default="fade",
        help=(
            "Processing mode. "
            "'fade' (default): blur the image and fade its edges to full "
            "transparency. Simple and robust, but can cut off illustration "
            "content near the border. "
            "'mirror-fade' (experimental): mirror-extends the border content "
            "outward before fading, so less of the original artwork is lost "
            "near the edges. See README.md for details."
        ),
    )
    parser.add_argument(
        "--fade-percent", type=float, default=15.0,
        help=(
            "Used in 'fade' mode. How much of the image, as a percentage "
            "(0-50) of its shorter side, is used as the fade zone near each "
            "edge. Higher = more of the picture fades out. Default: 15."
        ),
    )
    parser.add_argument(
        "--mirror-percent", type=float, default=12.0,
        help=(
            "Used in 'mirror-fade' mode. Percentage (0-50) of the image's "
            "shorter side that gets mirror-extended outward before the fade "
            "is applied. Default: 12."
        ),
    )
    parser.add_argument(
        "--blur-radius", type=int, default=None,
        help=(
            "Optional. Gaussian blur radius in pixels applied near the "
            "edges. If omitted, a sensible radius is derived automatically "
            "from --fade-percent / --mirror-percent."
        ),
    )
    return parser.parse_args()


# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------

def build_fade_mask(width, height, fade_px, blur_radius):
    """
    Build a smooth grayscale mask (as a 0..1 float array) that is fully
    opaque (1.0) in the center of the image and smoothly fades to 0.0 at
    the border, over a zone `fade_px` pixels wide.

    Instead of a hard-edged rectangle, the mask itself is Gaussian-blurred,
    so there is no sudden transition anywhere in the fade zone.
    """
    if fade_px <= 0:
        return np.ones((height, width), dtype=np.float32)

    mask = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(mask)
    draw.rectangle(
        [fade_px, fade_px, width - fade_px - 1, height - fade_px - 1],
        fill=255,
    )
    mask = mask.filter(ImageFilter.GaussianBlur(radius=blur_radius))
    return np.asarray(mask, dtype=np.float32) / 255.0


def blend_with_mask(image, mask, blur_radius):
    """
    Given an RGBA PIL image and a 0..1 float mask of the same size:
      - RGB is a blend of the sharp original and a blurred copy, weighted by
        the mask (sharp in the center, blurred near the edges). This avoids
        a hard color transition right where the alpha starts dropping.
      - Alpha is multiplied by the mask, so the image itself fades out
        towards the edges instead of being cut off.
    """
    blurred = image.filter(ImageFilter.GaussianBlur(radius=blur_radius))

    orig_arr = np.asarray(image, dtype=np.float32)
    blur_arr = np.asarray(blurred, dtype=np.float32)
    mask_3 = mask[..., None]

    blended_rgb = orig_arr[..., :3] * mask_3 + blur_arr[..., :3] * (1 - mask_3)

    orig_alpha = orig_arr[..., 3] / 255.0
    new_alpha = orig_alpha * mask

    out = np.dstack([blended_rgb, new_alpha * 255.0]).astype(np.uint8)
    return Image.fromarray(out, mode="RGBA")


# --------------------------------------------------------------------------
# Mode 1: fade (default)
# --------------------------------------------------------------------------

def apply_fade(image, fade_percent, blur_radius=None):
    """
    Default mode. Blurs and fades the image's own edges to transparency,
    with no attempt to preserve content that falls inside the fade zone.

    Known trade-off: if the interesting part of the illustration extends
    close to the border, some of it will visibly fade out. This is the
    "brute-force" mode; use 'mirror-fade' if that content loss is a problem
    for a given image.
    """
    image = image.convert("RGBA")
    width, height = image.size
    short_side = min(width, height)
    fade_px = max(1, int(short_side * (fade_percent / 100.0)))

    if blur_radius is None:
        blur_radius = max(2, fade_px // 2)

    mask = build_fade_mask(width, height, fade_px, blur_radius)
    return blend_with_mask(image, mask, blur_radius)


# --------------------------------------------------------------------------
# Mode 2: mirror-fade (experimental)
# --------------------------------------------------------------------------

def apply_mirror_fade(image, mirror_percent, blur_radius=None):
    """
    Experimental mode. Instead of fading the original border pixels straight
    to transparency, the border strip is first mirrored (reflected) outward,
    growing the canvas. That reflected strip is then blurred and faded out
    using the same logic as 'fade'.

    The idea: the mirrored strip is still *visually related* content (an
    echo of the artwork itself, not blank space), so the transition reads
    as a soft vignette rather than as the picture being cut off. This mode
    is a first pass and its parameters/approach may change - see
    README.md's "Known limitations / roadmap" section.
    """
    image = image.convert("RGBA")
    width, height = image.size
    short_side = min(width, height)
    mirror_px = max(1, int(short_side * (mirror_percent / 100.0)))

    if blur_radius is None:
        blur_radius = max(2, mirror_px // 2)

    arr = np.asarray(image, dtype=np.uint8)
    padded = np.pad(
        arr,
        pad_width=((mirror_px, mirror_px), (mirror_px, mirror_px), (0, 0)),
        mode="reflect",
    )
    padded_img = Image.fromarray(padded, mode="RGBA")
    pw, ph = padded_img.size

    mask = build_fade_mask(pw, ph, mirror_px, blur_radius)
    return blend_with_mask(padded_img, mask, blur_radius)


# --------------------------------------------------------------------------
# Batch processing
# --------------------------------------------------------------------------

def process_folder(args):
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    if not input_dir.exists():
        print(f"Input folder not found: {input_dir}", file=sys.stderr)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    images = sorted(
        p for p in input_dir.iterdir()
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTENSIONS
    )

    if not images:
        print(f"No supported images found in {input_dir}")
        return

    for path in images:
        try:
            with Image.open(path) as img:
                if args.mode == "fade":
                    result = apply_fade(img, args.fade_percent, args.blur_radius)
                else:  # mirror-fade
                    result = apply_mirror_fade(img, args.mirror_percent, args.blur_radius)

            out_path = output_dir / f"{path.stem}.png"
            result.save(out_path, format="PNG")
            print(f"Processed: {path.name} -> {out_path}")
        except Exception as exc:  # keep going even if one image fails
            print(f"Failed to process {path.name}: {exc}", file=sys.stderr)


def main():
    args = parse_args()
    process_folder(args)


if __name__ == "__main__":
    main()
